"""
Конфигурация системы потоковой передачи видео
"""

# === SERIAL PORT ===
SERIAL_PORT_TX = "/dev/ttyUSB0"
SERIAL_PORT_RX = "/dev/ttyUSB1"
SERIAL_BAUDRATE = 38400

# === PACKET STRUCTURE ===
PACKET_SIZE = 128
PACKETS_PER_SECOND = 25
PACKET_INTERVAL_MS = 40

# === PROTOCOL HEADER ===
SYNC_MAGIC = b'\xAA\xBB'
HEADER_SIZE = 5
PAYLOAD_SIZE = PACKET_SIZE - HEADER_SIZE  # 123 байта

# === FRAME TYPES ===
FRAME_TYPE_KEY = 0x01
FRAME_TYPE_DELTA = 0x02
FRAME_TYPE_CONTINUATION = 0x03

# === VIDEO PARAMETERS ===
FRAME_WIDTH = 128
FRAME_HEIGHT = 64
FRAME_PIXELS = FRAME_WIDTH * FRAME_HEIGHT

# === EDGE DETECTION ===
CANNY_THRESHOLD_1 = 180
CANNY_THRESHOLD_2 = 220
DILATE_KERNEL_SIZE = 1
DILATE_ITERATIONS = 1

# === CODEC ===
KEYFRAME_INTERVAL = 10

# === LEAKY BUCKET (уменьшено для низкой задержки!) ===
# Максимум ~2-3 пакета в буфере, не больше
BUCKET_MAX_SIZE = PACKET_SIZE * 30  # ~384 байт = 3 пакета

# === TIMING ===
CAMERA_FPS_TARGET = 15  # Уменьшено чтобы не создавать очередь
DISPLAY_WAIT_MS = 1

# === DEBUG ===
DEBUG_PRINT_STATS = True
STATS_INTERVAL_SEC = 2